- name: variables to print
 hosts: web
  vars:
   Course: "Ansible"
  vars_files:
   - vars.yaml
  vars_promt:
   - name: Course
    promt: print the course info
    private: false # not confidential by default if we not mention it is going to be confidential
 tasks:
   - name: print the info
     vars: 
       Course: "Devops with aws"
         ansible.builtin.debug:
         msg: "Hi, I am learning {{Course}}"

#1. command line/args --> first it is goin to take from args we need give input
#2. Task level
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles