- name: loops demo
  hosts: web
  become: yes
  tasks:
   - name: install packages
     ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
      loop:
      - {name: 'mysql', state: 'present'}    # this is one complete item
      - {name: 'nginx', state: 'absent'}
      - { name: 'postfix', state: 'absent'}
      - { name: 'nginx', state: 'present'}

# ansible-playbook -i inventory.ini 18-loops.yaml